// <auto-generated />
using System;
using AttendUp.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendUp.Mvc.Migrations
{
    [DbContext(typeof(AttendUpContext))]
    partial class AttendUpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AttendUp.Mvc.Models.AuditLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Action = "Aangemaakt",
                            Details = "(ID: 1) Training 'Winter Kickoff' aangemaakt",
                            Timestamp = new DateTime(2025, 10, 15, 14, 22, 10, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 2,
                            Action = "Aangemaakt",
                            Details = "(ID: 2) Training 'Winter Session' aangemaakt.",
                            Timestamp = new DateTime(2025, 10, 15, 14, 25, 0, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 3,
                            Action = "Aangepast",
                            Details = "(ID: 6) Training 'New Year Training' gewijzigd.",
                            Timestamp = new DateTime(2025, 12, 28, 11, 5, 43, 0, DateTimeKind.Unspecified),
                            User = "Superadmin Superadmin"
                        },
                        new
                        {
                            ID = 4,
                            Action = "Verwijderd",
                            Details = "(ID: 99) Training 'Oude Test Training' permanent verwijderd inclusief 15 bijbehorende registraties.",
                            Timestamp = new DateTime(2026, 1, 10, 9, 15, 22, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 5,
                            Action = "Aangepast",
                            Details = "(ID: 18) Training 'Toertocht' is GEDEACTIVEERD. Reden: Slechte weersomstandigheden (storm).",
                            Timestamp = new DateTime(2026, 3, 28, 17, 40, 11, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 6,
                            Action = "Aangepast",
                            Details = "(ID: 18) Training 'Toertocht' is op ACTIEF gezet.",
                            Timestamp = new DateTime(2026, 3, 29, 7, 30, 0, 0, DateTimeKind.Unspecified),
                            User = "Superadmin Superadmin"
                        },
                        new
                        {
                            ID = 7,
                            Action = "Aangemaakt",
                            Details = "(ID: 28) Training 'June Training' aangemaakt.",
                            Timestamp = new DateTime(2026, 5, 20, 19, 2, 15, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 8,
                            Action = "Aangemaakt",
                            Details = "(ID: 29) Training 'June Training' aangemaakt.",
                            Timestamp = new DateTime(2026, 5, 20, 19, 4, 50, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 9,
                            Action = "Aangemaakt",
                            Details = "(ID: 30) Training 'June Training' aangemaakt.",
                            Timestamp = new DateTime(2026, 5, 20, 19, 6, 12, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 10,
                            Action = "Aangemaakt",
                            Details = "(ID: 31) Training 'Summer Ride' aangemaakt.",
                            Timestamp = new DateTime(2026, 5, 20, 19, 10, 5, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 11,
                            Action = "Aanpassen",
                            Details = "(ID: 31) Training 'Summer Ride' gewijzigd.",
                            Timestamp = new DateTime(2026, 5, 22, 10, 15, 30, 0, DateTimeKind.Unspecified),
                            User = "SuperAdmin SuperAdmin"
                        },
                        new
                        {
                            ID = 12,
                            Action = "Aangemaakt",
                            Details = "(ID: 32) Training 'July Training' aangemaakt.",
                            Timestamp = new DateTime(2026, 6, 15, 9, 30, 22, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 13,
                            Action = "Aangemaakt",
                            Details = "(ID: 33) Training 'July Training' aangemaakt.",
                            Timestamp = new DateTime(2026, 6, 15, 9, 32, 45, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 14,
                            Action = "Aangemaakt",
                            Details = "(ID: 34) Training 'July Training' aangemaakt.",
                            Timestamp = new DateTime(2026, 6, 15, 9, 35, 10, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 15,
                            Action = "Aangemaakt",
                            Details = "(ID: 35) Training 'End Ride' aangemaakt.",
                            Timestamp = new DateTime(2026, 6, 15, 9, 40, 0, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 16,
                            Action = "Aangepast",
                            Details = "(ID: 33) Training 'July Training' is GEDEACTIVEERD. Reden: Extreme hittegolf voorspeld (>35°C).",
                            Timestamp = new DateTime(2026, 7, 10, 14, 22, 18, 0, DateTimeKind.Unspecified),
                            User = "SuperAdmin SuperAdmin"
                        },
                        new
                        {
                            ID = 17,
                            Action = "Aangemaakt",
                            Details = "(ID: 36) Training 'September Restart' aangemaakt.",
                            Timestamp = new DateTime(2026, 8, 20, 11, 14, 55, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 18,
                            Action = "Aangemaakt",
                            Details = "(ID: 37) Training 'September Training' aangemaakt.",
                            Timestamp = new DateTime(2026, 8, 20, 11, 16, 40, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 19,
                            Action = "Aangemaakt",
                            Details = "(ID: 38) Training 'September Training' aangemaakt.",
                            Timestamp = new DateTime(2026, 8, 20, 11, 18, 12, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 20,
                            Action = "Aangemaakt",
                            Details = "(ID: 39) Training 'Autumn Ride' aangemaakt.",
                            Timestamp = new DateTime(2026, 8, 20, 11, 22, 1, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        },
                        new
                        {
                            ID = 21,
                            Action = "Verwijderd",
                            Details = "(ID: 88) Training 'Test Sessie Herfst' permanent verwijderd inclusief 3 bijbehorende registraties.",
                            Timestamp = new DateTime(2026, 9, 2, 16, 45, 33, 0, DateTimeKind.Unspecified),
                            User = "SuperAdmin SuperAdmin"
                        },
                        new
                        {
                            ID = 22,
                            Action = "Aangepast",
                            Details = "(ID: 36) Training 'September Restart' gewijzigd.",
                            Timestamp = new DateTime(2026, 9, 4, 10, 8, 19, 0, DateTimeKind.Unspecified),
                            User = "Admin Admin"
                        });
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.Family", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamilyId"));

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerPersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FamilyId");

                    b.HasIndex("OwnerPersonId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.FamilyMember", b =>
                {
                    b.Property<int>("FamilyMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamilyMemberId"));

                    b.Property<int>("FamilyId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FamilyMemberId");

                    b.HasIndex("FamilyId");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Expo Roeselare"
                        });
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.PasswordExpiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsBlockedDueToExpiry")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastPasswordChanged")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PasswordExpiries");
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.Registration", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnName("isValid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubActivityID")
                        .HasColumnType("int");

                    b.Property<int>("TrainingID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("LocationId");

                    b.HasIndex("SubActivityID");

                    b.HasIndex("TrainingID");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.Setting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BoardSessionTimeoutMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ButtonColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultBackgroundColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultButtonColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventBannerPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegistrationWindowMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("StoreIpAddresses")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BackgroundColor = "#f0f4f8",
                            BoardSessionTimeoutMinutes = 60,
                            ButtonColor = "#FF6600",
                            DefaultBackgroundColor = "#1A1A2E",
                            DefaultButtonColor = "#FF6600",
                            LogoPath = "/images/logo.png",
                            RegistrationWindowMinutes = 30,
                            StoreIpAddresses = false
                        });
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.SubActivity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SubActivity");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            IsActive = true,
                            Name = "Basistraining"
                        },
                        new
                        {
                            ID = 2,
                            IsActive = true,
                            Name = "Hockey"
                        },
                        new
                        {
                            ID = 3,
                            IsActive = true,
                            Name = "Toerentocht"
                        });
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Exception")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.Training", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeactivationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Training");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Date = new DateTime(2025, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Winter Kickoff"
                        },
                        new
                        {
                            ID = 2,
                            Date = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Winter Session"
                        },
                        new
                        {
                            ID = 3,
                            Date = new DateTime(2025, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Winter Session"
                        },
                        new
                        {
                            ID = 4,
                            Date = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Winter Session"
                        },
                        new
                        {
                            ID = 5,
                            Date = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Winter Session"
                        },
                        new
                        {
                            ID = 6,
                            Date = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "New Year Training"
                        },
                        new
                        {
                            ID = 7,
                            Date = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "January Session"
                        },
                        new
                        {
                            ID = 8,
                            Date = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "January Session"
                        },
                        new
                        {
                            ID = 9,
                            Date = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "January Session"
                        },
                        new
                        {
                            ID = 10,
                            Date = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 11,
                            Date = new DateTime(2026, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 12,
                            Date = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 13,
                            Date = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 14,
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 15,
                            Date = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 16,
                            Date = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 17,
                            Date = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 18,
                            Date = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Toertocht"
                        },
                        new
                        {
                            ID = 19,
                            Date = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 20,
                            Date = new DateTime(2026, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 21,
                            Date = new DateTime(2026, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 22,
                            Date = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 23,
                            Date = new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 24,
                            Date = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 25,
                            Date = new DateTime(2026, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Training"
                        },
                        new
                        {
                            ID = 26,
                            Date = new DateTime(2026, 5, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 19, 30, 0, 0),
                            Title = "Open Ride"
                        },
                        new
                        {
                            ID = 27,
                            Date = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            Title = "Festival Ride"
                        },
                        new
                        {
                            ID = 28,
                            Date = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "June Training"
                        },
                        new
                        {
                            ID = 29,
                            Date = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "June Training"
                        },
                        new
                        {
                            ID = 30,
                            Date = new DateTime(2026, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "June Training"
                        },
                        new
                        {
                            ID = 31,
                            Date = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Summer Ride"
                        },
                        new
                        {
                            ID = 32,
                            Date = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "July Training"
                        },
                        new
                        {
                            ID = 33,
                            Date = new DateTime(2026, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "July Training"
                        },
                        new
                        {
                            ID = 34,
                            Date = new DateTime(2026, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "July Training"
                        },
                        new
                        {
                            ID = 35,
                            Date = new DateTime(2026, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "End Ride"
                        },
                        new
                        {
                            ID = 36,
                            Date = new DateTime(2026, 9, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "September Restart"
                        },
                        new
                        {
                            ID = 37,
                            Date = new DateTime(2026, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "September Training"
                        },
                        new
                        {
                            ID = 38,
                            Date = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "September Training"
                        },
                        new
                        {
                            ID = 39,
                            Date = new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Autumn Ride"
                        },
                        new
                        {
                            ID = 40,
                            Date = new DateTime(2026, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "October Training"
                        },
                        new
                        {
                            ID = 41,
                            Date = new DateTime(2026, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "October Training"
                        },
                        new
                        {
                            ID = 42,
                            Date = new DateTime(2026, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "October Training"
                        },
                        new
                        {
                            ID = 43,
                            Date = new DateTime(2026, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 21, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 18, 0, 0, 0),
                            Title = "Halloween Ride"
                        },
                        new
                        {
                            ID = 44,
                            Date = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "November Training"
                        },
                        new
                        {
                            ID = 45,
                            Date = new DateTime(2026, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "November Training"
                        },
                        new
                        {
                            ID = 46,
                            Date = new DateTime(2026, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "November Training"
                        },
                        new
                        {
                            ID = 47,
                            Date = new DateTime(2026, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Winter Prep"
                        },
                        new
                        {
                            ID = 48,
                            Date = new DateTime(2026, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "December Training"
                        },
                        new
                        {
                            ID = 49,
                            Date = new DateTime(2026, 12, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "December Training"
                        },
                        new
                        {
                            ID = 50,
                            Date = new DateTime(2026, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Year End Ride"
                        },
                        new
                        {
                            ID = 51,
                            Date = new DateTime(2027, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "Kickoff 2027"
                        },
                        new
                        {
                            ID = 52,
                            Date = new DateTime(2027, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "January Training"
                        },
                        new
                        {
                            ID = 53,
                            Date = new DateTime(2027, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "January Training"
                        },
                        new
                        {
                            ID = 54,
                            Date = new DateTime(2027, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            IsActive = true,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Title = "January Training"
                        });
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.TrainingSubActivity", b =>
                {
                    b.Property<int>("TrainingID")
                        .HasColumnType("int");

                    b.Property<int>("SubActivityID")
                        .HasColumnType("int");

                    b.HasKey("TrainingID", "SubActivityID");

                    b.HasIndex("SubActivityID");

                    b.ToTable("TrainingSubActivity");

                    b.HasData(
                        new
                        {
                            TrainingID = 1,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 1,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 1,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 2,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 2,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 2,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 3,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 3,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 3,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 4,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 4,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 4,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 5,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 5,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 5,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 6,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 6,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 6,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 7,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 7,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 7,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 8,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 8,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 8,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 9,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 9,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 9,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 10,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 10,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 10,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 11,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 11,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 11,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 12,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 12,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 12,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 13,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 13,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 13,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 14,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 14,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 14,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 15,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 15,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 15,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 16,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 16,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 16,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 17,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 17,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 17,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 18,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 18,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 18,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 19,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 19,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 19,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 20,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 20,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 20,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 21,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 21,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 21,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 22,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 22,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 22,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 23,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 23,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 23,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 24,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 24,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 24,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 25,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 25,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 25,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 26,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 27,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 28,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 28,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 29,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 29,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 30,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 30,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 31,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 32,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 32,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 33,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 33,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 34,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 34,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 35,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 36,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 36,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 37,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 37,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 38,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 38,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 39,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 40,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 40,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 41,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 41,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 42,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 42,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 43,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 44,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 44,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 45,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 45,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 46,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 46,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 47,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 48,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 48,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 49,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 49,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 50,
                            SubActivityID = 3
                        },
                        new
                        {
                            TrainingID = 51,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 51,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 52,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 52,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 53,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 53,
                            SubActivityID = 2
                        },
                        new
                        {
                            TrainingID = 54,
                            SubActivityID = 1
                        },
                        new
                        {
                            TrainingID = 54,
                            SubActivityID = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.Family", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "OwnerPerson")
                        .WithMany()
                        .HasForeignKey("OwnerPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerPerson");
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.FamilyMember", b =>
                {
                    b.HasOne("AttendUp.Mvc.Models.Family", "Family")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.Registration", b =>
                {
                    b.HasOne("AttendUp.Mvc.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendUp.Mvc.Models.SubActivity", "SubActivity")
                        .WithMany()
                        .HasForeignKey("SubActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendUp.Mvc.Models.Training", "Training")
                        .WithMany()
                        .HasForeignKey("TrainingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("SubActivity");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.TrainingSubActivity", b =>
                {
                    b.HasOne("AttendUp.Mvc.Models.SubActivity", "SubActivity")
                        .WithMany("TrainingSubActivities")
                        .HasForeignKey("SubActivityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AttendUp.Mvc.Models.Training", "Training")
                        .WithMany("TrainingSubActivities")
                        .HasForeignKey("TrainingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubActivity");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.Family", b =>
                {
                    b.Navigation("FamilyMembers");
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.SubActivity", b =>
                {
                    b.Navigation("TrainingSubActivities");
                });

            modelBuilder.Entity("AttendUp.Mvc.Models.Training", b =>
                {
                    b.Navigation("TrainingSubActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
